### ISSUE TITLE
Feedback: Explain how to download data from repository

### ISSUE THREAD

**Issue by EKuki** [nsbatra/Epi_R_handbook#121]
https://github.com/nsbatra/Epi_R_handbook/blob/c9ae0abc67929fb930628762c860bd744648485f/docs/data-and-session-info.html#L121

Some people may need instructions on how to download the data from a Github repository.

**Comment by nsbatra** [comment]
Addressed now. 
Added step-by-step with screenshots for the different data types hosted on Github (xlsx, rds, csv, shp...). 
Also added a "Download from Github" section to the Import and Export page
Also moved the steps to download the Offline book to this same data/download page.
