### ISSUE TITLE
Feedback: Add link to Working with dates

### ISSUE THREAD

**Issue by EKuki** [nsbatra/Epi_R_handbook#122]
https://github.com/nsbatra/Epi_R_handbook/blob/c9ae0abc67929fb930628762c860bd744648485f/docs/r-basics.html#L564

Maybe add a link to the "working with dates" section.

**Comment by EKuki** [comment]
Sure.
But I haven't provided that much input yet!
I will continue going through the book until the deadline.
It looks really good, you guys have done a great work.

Esther

**Comment by nsbatra** [comment]
Addressed. Will show in the new refresh of the handbook.
