### ISSUE TITLE
# Feedback: Show how to see the data once imported

### ISSUE THREAD

**Issue by EKuki** [nsbatra/Epi_R_handbook#125]
https://github.com/nsbatra/Epi_R_handbook/blob/ee06d4aa7036acc54092064582d32c27ac1261b4/docs/import-and-export.html#L299

Here we are showing how the data looks like if we have a second header row. A new R user, may not know about the head() function and may be wondering how did you produced the outcome of the first rows of a table. The first time head() appears in the book is a bit after these lines. Maybe introduce the head() function the first time we use import(). I noticed the same when going over the section "34 Diagrams", though if we deal with it here, we don't need to worry about it later on.

**Comment by nsbatra** [comment]
Thanks @EKuki I added a line for clarification that that double-header dataset is only displayed as an example. I've also added explanation about head() in the Cleaning page in the section on reviewing your data.
