### ISSUE TITLE
Feedback: Typo?

### ISSUE THREAD

**Issue by EKuki** [nsbatra/Epi_R_handbook#126]
https://github.com/nsbatra/Epi_R_handbook/blob/ee06d4aa7036acc54092064582d32c27ac1261b4/docs/diagrams.html#L243

Is "A label is also necessary" a typo? It seems that we wanted to say something else here but we never finished the sentence.
As it is now, the sentence reads "A label is also necessary to have a newline within the node name - use \n in the node label within single quotes, as shown below."

**Comment by nsbatra** [comment]
Thanks @EKuki  I've revised this sentence now
