### ISSUE TITLE
Feedback: Aesthetic suggestion 

### ISSUE THREAD

**Issue by EKuki** [nsbatra/Epi_R_handbook#127]
https://github.com/nsbatra/Epi_R_handbook/blob/ee06d4aa7036acc54092064582d32c27ac1261b4/docs/diagrams.html#L232
Consider adding a few spaces after the first single quote for each edge label, so they get separated from the edge line.
From: label = 'case transfer'
to: label = '     case transfer' # Note the extra spaces

**Comment by nsbatra** [comment]
Good idea! Implemented
