### ISSUE TITLE
Feebdback: Remove semicolon for consistency and simplicity

### ISSUE THREAD

**Issue by EKuki** [nsbatra/Epi_R_handbook#128]
https://github.com/nsbatra/Epi_R_handbook/blob/ee06d4aa7036acc54092064582d32c27ac1261b4/docs/diagrams.html#L460

When creating an edge originating in different nodes that is pointing to the same destination node, I was wondering why we needed a semicolon ";" here:
 {'Social Media'; Radio} -> EBS
when we didn't need it here:
 {Primary Secondary Tertiary} -> SC [label = 'case reporting']

It seems the semicolon separating the origin nodes is not necessary.
 {'Social Media' Radio} -> EBS
works as well.

Consider removing the semicolon, for consistency and simplicity.

**Comment by EKuki** [comment]
Same recommendation (remove semicolons) in subgraphs, after each node has been named:

Change:
  subgraph cluster_active {
    Active [label = 'Active\nSurveillance']; 
    HCF_active [label = 'HCF\nActive Search']
  }
  
  subgraph cluster_EBD {
    EBS [label = 'Event-Based\nSurveillance (EBS)']; 
    'Social Media'
    Radio
  }
  
  subgraph cluster_CBS {
    CBS [label = 'Community-Based\nSurveillance (CBS)'];
    RECOs
  }


To:
  subgraph cluster_EBD {
    EBS [label = 'Event-Based\nSurveillance (EBS)'] 
    'Social Media'
    Radio
  }
  
  subgraph cluster_CBS {
    CBS [label = 'Community-Based\nSurveillance (CBS)']
    RECOs
  }

  subgraph cluster_CBS {
    CBS [label = 'Community-Based\nSurveillance (CBS)']
    RECOs
  }

**Comment by nsbatra** [comment]
Thanks for catching this! I appreciate your attention to this detail. I've revised this now.
