### ISSUE TITLE
Feedback: Reorder age_cat in plot

### ISSUE THREAD

**Issue by EKuki** [nsbatra/Epi_R_handbook#130]
https://github.com/nsbatra/Epi_R_handbook/blob/e209be03bfb92c71ae028d951b90a0e9a370faee/docs/diagrams.html#L576

Consider reordering the age categories so they are presented in the right order in the Sankey diagram.
Maybe something like this (will need to add a better comment explaining what we are doing here): 
nodes <- nodes %>%  slice(1:7,12,8:11, 13, 15, 14) # Rearrange the row order of age_cat
before matching to numbers. 

Then, add the argument "iterations = 0" to the sankeyNetwork() function:

sankeyNetwork(Links = links,
                   Nodes = nodes,
                   Source = "IDsource",
                   Target = "IDtarget",
                   Value = "n",
                   NodeID = "name",
                   units = "TWh",
                   fontSize = 12,
                   nodeWidth = 30,
                   **iterations = 0**)

**Comment by EKuki** [comment]
Or maybe this would be more intuitive:
nodes$name[7:15] <- c("0-4", "5-9", "10-14", "15-19", "20-29", "30-49", "50-69", "70+", NA) # Rearrange the row order of age_cat

**Comment by EKuki** [comment]
Or maybe this would be more intuitive:
nodes$name[7:15] <- c("0-4", "5-9", "10-14", "15-19", "20-29", "30-49", "50-69", "70+", NA)

**Comment by nsbatra** [comment]
THanks @EKuki . For ease I've just filtered out NA age_cat in an earlier step, but I've added iteration = 0 and explained it so now the age categories are ordered correctly. I've also spent expanded the text explanations of this section.
