### ISSUE TITLE
Editorial decisions page

### ISSUE THREAD

**Issue by nsbatra** [nsbatra/Epi_R_handbook#36]
@aspina7  @isaac-florence @henryls1 @PBBlomquist 

Perhaps we include a page in the handbook that briefly describes each major editorial decision? E.g. for choosing between epiweek packages, factoring packages, stringr vs. paste0, terminology, etc.?

A good idea?

**Comment by PBBlomquist** [comment]
Hi Neale. Is this like an easy-to-find version control/log for us? Agree need something like this, not sure if should be handbook itself or somewhere behind the scenes (e.g. in the handbook guide for developers)?

**Comment by nsbatra** [comment]
@PBBlomquist I was thinking this would be more front-facing, like a brief justification to any interested reader why we chose what we chose. Contribution guide would have more detailed guidelines for contibutors.

**Comment by lizacoyer** [comment]
@nsbatra Yea I agree logging would be good. Perhaps a good place for it would be the overview tab of the respective page? Seeing that the pages are usually grouped by what we aim to do, it would be good to justify there why we choose to use a certain package. But perhaps a general page for decisions that don't fit above would be useful.

**Comment by aspina7** [comment]
think good idea! Agree with liza a page specific one and and overview page definitely useful

**Comment by nsbatra** [comment]
There is now a high-level editorial decisions section in the Style page (in the About this Handbook section).
