### ISSUE TITLE
Duplicated ID in linelist_cleaned

### ISSUE THREAD

**Issue by finlaycampbell** [nsbatra/Epi_R_handbook#58]
A single ID is duplicated in `linelist_cleaned` (40b34f). If this is meant to be the case I'm happy to leave it in and will just manually remove it for the epicontacts analysis, I'm not sure if it is though!

**Comment by nsbatra** [comment]
Let me look into this soon! You can manually remove for the moment
Thanks for catching

**Comment by nsbatra** [comment]
I re-arranged the data cleaning script so I think there should be no more
duplicate IDs. It was an artifact because I created a second (earlier)
outbreak that I filtered out in the cleaning page (to demonstrate
filtering).
